/**
 * Research — the assistant and the report generator.
 *
 * The assistant holds no independent knowledge of the circuit: it can only quote
 * the objects this page hands it, and it says which ones it received.  Reports are
 * generated by re-running the operation they describe, so a report is reproducible
 * by construction rather than a transcription of the screen.
 */

import { useMemo, useState } from "react";
import { AnimatedNumber, InView } from "../components/motion";
import type { ModeKey } from "../components/Shell";
import {
  Button,
  CodeBlock,
  DataTable,
  Empty,
  Field,
  KeyValueList,
  Notice,
  Panel,
  SectionTitle,
  Select,
  StatTile,
  Tag,
  TextInput,
  Toggle,
} from "../components/ui";
import { api, type ReportPayload, type StoredExperiment } from "../lib/api";
import { formatBytes, titleCase } from "../lib/format";
import { useStore } from "../state/store";

const REPORT_KINDS = [
  { value: "simulation", label: "simulation", needs: "the loaded circuit" },
  { value: "experiment", label: "experiment", needs: "the most recent sweep run here" },
  { value: "optimization", label: "optimization", needs: "the loaded circuit" },
  { value: "trace", label: "trace", needs: "the loaded circuit" },
  { value: "comparison", label: "comparison", needs: "the loaded circuit and a second one" },
  { value: "evolution", label: "evolution", needs: "the loaded circuit" },
  { value: "hardware", label: "hardware mapping", needs: "the loaded circuit and a device" },
];

function renderBody(body: unknown) {
  if (body === null || body === undefined || body === "") return <p className="text-[11px] text-[var(--c-faint)]">—</p>;
  if (typeof body === "string" || typeof body === "number") return <p className="text-[11px] leading-relaxed text-[var(--c-muted)]">{String(body)}</p>;
  if (Array.isArray(body)) {
    const first = body[0];
    if (first !== null && typeof first === "object" && !Array.isArray(first)) {
      const columns = Object.keys(first as Record<string, unknown>).slice(0, 8);
      return (
        <DataTable
          columns={columns.map((key) => ({
            key,
            label: key.replace(/_/g, " "),
            render: (row: Record<string, unknown>) => {
              const value = row[key];
              if (value === null || value === undefined) return "—";
              if (typeof value === "object") return <span className="mono-num text-[10px]">{JSON.stringify(value)}</span>;
              return typeof value === "number" ? value.toPrecision(5) : String(value);
            },
          }))}
          rows={body as Array<Record<string, unknown>>}
        />
      );
    }
    return (
      <ul className="space-y-1.5">
        {(body as unknown[]).map((entry, index) => (
          <li key={index} className="flex items-start gap-2 text-[11px] leading-relaxed text-[var(--c-muted)]">
            <span className="mt-[5px] h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--c-primary)]" />
            {typeof entry === "object" ? JSON.stringify(entry) : String(entry)}
          </li>
        ))}
      </ul>
    );
  }
  return (
    <KeyValueList
      columns={2}
      items={Object.entries(body as Record<string, unknown>).map(([label, value]) => ({
        label: label.replace(/_/g, " "),
        value: typeof value === "object" && value !== null ? JSON.stringify(value) : String(value ?? "—"),
      }))}
    />
  );
}

export function ResearchMode({ onNavigate }: { onNavigate: (mode: ModeKey) => void }) {
  const {
    meta,
    health,
    settings,
    document: circuit,
    result,
    trace,
    optimization,
    experiment,
    compareResult,
    history,
    answer,
    report,
    loading,
    errors,
    ask,
    buildReport,
    exportReport,
  } = useStore();

  const [question, setQuestion] = useState("Why did the fidelity decrease?");
  const [useLlm, setUseLlm] = useState(false);
  const [include, setInclude] = useState({ circuit: true, simulation: true, trace: true, optimize: true, hardware: false });
  const [deviceChoice, setDeviceChoice] = useState("");
  const [storedIds, setStoredIds] = useState<string[]>([]);
  const [reportKind, setReportKind] = useState("simulation");
  const [reportTitle, setReportTitle] = useState("");
  const [reportObjective, setReportObjective] = useState("");
  const [otherAlgorithm, setOtherAlgorithm] = useState("ghz_state");
  const [savedFiles, setSavedFiles] = useState<Array<{ name: string; bytes: number; modified: string; format: string }>>([]);
  const [savedDir, setSavedDir] = useState("");
  const [localError, setLocalError] = useState("");

  const suggestions = meta?.ai_suggestions ?? [];
  const source = circuit ? { circuit } : null;
  const devices = meta?.hardware ?? [];
  const device = devices.some((entry) => entry.key === deviceChoice) ? deviceChoice : devices[0]?.key ?? "";

  const currentNoise = () => {
    if (settings.noiseStrength > 0) {
      const base =
        settings.noise.name && settings.noise.name !== "ideal"
          ? settings.noise
          : { name: "depolarizing", params: { p: 0.05 } };
      return { ...base, scale: settings.noiseStrength };
    }
    return settings.noise;
  };

  const askBody = () => {
    const body: Record<string, unknown> = {
      question,
      use_llm: useLlm && Boolean(health?.llm_configured),
    };
    if (source && include.circuit) body.source = source;
    if (source && include.simulation) {
      body.simulate = {
        source,
        shots: settings.shots,
        seed: settings.seed,
        backend: settings.backend,
        noise: currentNoise(),
        compare_ideal: true,
        store: false,
      };
    }
    if (source && include.trace) {
      body.trace = { source, depth: settings.traceDepth, term_limit: settings.termLimit, max_steps: null };
    }
    if (source && include.optimize) {
      body.optimize = { source, level: settings.optimizerLevel, verify: settings.verify };
    }
    if (source && include.hardware) {
      body.hardware = { source, device, route: true };
    }
    if (storedIds.length) body.experiment_ids = storedIds.slice(0, 8);
    return body;
  };

  /** The report payload for the selected kind, or a reason it cannot be built. */
  const reportRequest = (): { ok: true; payload: Record<string, unknown> } | { ok: false; reason: string } => {
    if (!source) return { ok: false, reason: "Load a circuit in Build first — every report is built from a real run." };
    switch (reportKind) {
      case "simulation":
        return {
          ok: true,
          payload: {
            source,
            shots: settings.shots,
            seed: settings.seed,
            backend: settings.backend,
            noise: currentNoise(),
            compare_ideal: true,
            store: false,
          },
        };
      case "optimization":
        return { ok: true, payload: { source, level: settings.optimizerLevel, verify: settings.verify } };
      case "trace":
        return { ok: true, payload: { source, depth: settings.traceDepth, term_limit: settings.termLimit, max_steps: null } };
      case "comparison":
        return {
          ok: true,
          payload: {
            a: source,
            b: { algorithm: otherAlgorithm },
            shots: settings.shots,
            seed: settings.seed,
            backend: settings.backend,
            noise: currentNoise(),
          },
        };
      case "evolution":
        return { ok: true, payload: { source, generations: 6, population: 8, seed: settings.seed, target: "circuit" } };
      case "hardware":
        return { ok: true, payload: { source, device, route: true } };
      case "experiment": {
        if (!experiment) return { ok: false, reason: "Run a sweep in the Experiment laboratory first." };
        const spec = experiment.spec as Record<string, unknown>;
        const axes = Array.isArray(spec.axes)
          ? Object.fromEntries(
              (spec.axes as Array<{ name: string; values: Array<number | string> }>).map((axis) => [axis.name, axis.values]),
            )
          : {};
        return {
          ok: true,
          payload: {
            key: String(spec.key ?? "experiment"),
            kind: String(spec.kind ?? "custom"),
            algorithm: typeof spec.algorithm === "string" ? spec.algorithm : undefined,
            axes,
            fixed: (spec.fixed as Record<string, unknown>) ?? {},
            shots: Number(spec.shots ?? settings.shots),
            seed: Number(spec.seed ?? settings.seed),
            backend: String(spec.backend ?? settings.backend),
            noise: (spec.noise as Record<string, unknown>) ?? currentNoise(),
            store: false,
          },
        };
      }
      default:
        return { ok: false, reason: "Unknown report kind." };
    }
  };

  const build = () => {
    const request = reportRequest();
    if (!request.ok) {
      setLocalError(request.reason);
      return;
    }
    setLocalError("");
    void buildReport(reportKind, request.payload, reportTitle || `${titleCase(reportKind)} report`, reportObjective || undefined);
    void api
      .listReports()
      .then((payload) => {
        setSavedFiles(payload.files);
        setSavedDir(payload.dir);
      })
      .catch(() => undefined);
  };

  const reportBody: ReportPayload["report"] | null = report?.report ?? null;
  const attached = useMemo(
    () =>
      [
        include.circuit && source ? "circuit" : null,
        include.simulation && source ? "simulation result" : null,
        include.trace && source ? "gate-by-gate trace" : null,
        include.optimize && source ? "optimization with verification" : null,
        include.hardware && source ? `hardware report (${device})` : null,
        storedIds.length ? `${storedIds.length} stored run(s)` : null,
      ].filter((entry): entry is string => entry !== null),
    [include, source, device, storedIds],
  );

  return (
    <div className="space-y-4">
      <div className="grid gap-4 xl:grid-cols-[400px_1fr]">
        {/* -------------------------------------------------------- assistant */}
        <div className="space-y-3">
          <Panel title="Ask the assistant" subtitle="Grounded in the objects you attach. Never in a language model's memory of quantum computing." dense>
            <div className="space-y-3">
              <Field label="question" hint="Numbers you already have are safe to quote — the assistant reads them from the attached objects.">
                <textarea
                  className="focus-ring w-full rounded-lg border border-[var(--c-line)] bg-[color-mix(in_oklab,var(--c-bg)_70%,transparent)] px-2.5 py-1.5 text-[12px] text-[var(--c-text)]"
                  rows={3}
                  value={question}
                  onChange={(event) => setQuestion(event.target.value)}
                />
              </Field>

              <div className="flex flex-wrap gap-1.5">
                {suggestions.map((entry) => (
                  <Button key={entry.intent} size="sm" variant="outline" title={`intent: ${entry.intent}`} onClick={() => setQuestion(entry.question)}>
                    {entry.question}
                  </Button>
                ))}
              </div>

              <div className="space-y-1.5">
                <SectionTitle hint="what the server receives with the question">attached context</SectionTitle>
                <Toggle checked={include.circuit} onChange={(value) => setInclude((current) => ({ ...current, circuit: value }))} label="circuit" />
                <Toggle
                  checked={include.simulation}
                  onChange={(value) => setInclude((current) => ({ ...current, simulation: value }))}
                  label={`simulation (${settings.shots} shots, seed ${settings.seed}, ${settings.backend})`}
                />
                <Toggle checked={include.trace} onChange={(value) => setInclude((current) => ({ ...current, trace: value }))} label="gate-by-gate trace" />
                <Toggle checked={include.optimize} onChange={(value) => setInclude((current) => ({ ...current, optimize: value }))} label="optimization and its verification" />
                <Toggle checked={include.hardware} onChange={(value) => setInclude((current) => ({ ...current, hardware: value }))} label="hardware estimate" />
                {include.hardware && (
                  <Select
                    value={device}
                    options={devices.map((entry) => ({ value: entry.key, label: `${entry.name} · ${entry.num_qubits}q` }))}
                    onChange={setDeviceChoice}
                  />
                )}
              </div>

              {history.length > 0 && (
                <div className="space-y-1.5">
                  <SectionTitle hint="max 8, from the history database">stored runs to quote</SectionTitle>
                  <div className="max-h-40 space-y-1 overflow-y-auto pr-1">
                    {history.slice(0, 12).map((entry: StoredExperiment) => (
                      <button
                        key={entry.experiment_id}
                        type="button"
                        onClick={() =>
                          setStoredIds((current) =>
                            current.includes(entry.experiment_id)
                              ? current.filter((id) => id !== entry.experiment_id)
                              : [...current, entry.experiment_id].slice(-8),
                          )
                        }
                        className={`focus-ring w-full rounded-md border px-2 py-1 text-left text-[10px] transition-colors ${
                          storedIds.includes(entry.experiment_id)
                            ? "border-[var(--c-primary)] text-[var(--c-primary)]"
                            : "border-[var(--c-line)] text-[var(--c-muted)]"
                        }`}
                      >
                        {entry.created_at.slice(5, 19).replace("T", " ")} · {entry.name} · {entry.num_qubits}q · {entry.mode}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              <Toggle
                checked={useLlm}
                onChange={setUseLlm}
                label={health?.llm_configured ? "optionally rewrite the answer with the configured LLM" : "LLM narration (no endpoint configured — the offline answer is unaffected)"}
              />

              <div className="flex flex-wrap gap-2">
                <Button variant="primary" disabled={loading.ask || !question.trim()} onClick={() => void ask(askBody())}>
                  {loading.ask ? "reading your data…" : "ask"}
                </Button>
                <Button variant="outline" onClick={() => onNavigate("experiment")}>
                  run an experiment →
                </Button>
              </div>

              {errors.ask && <Notice tone="danger" title="The question was refused">{errors.ask}</Notice>}
              <Notice tone="info" title="How grounding works here">
                The assistant classifies the question, reads the attached objects, and answers from their numbers. With no
                LLM configured it still answers — entirely offline. If an LLM is configured, it may only rewrite the
                wording: every number in the narrative is checked against the grounded answer.
              </Notice>
            </div>
          </Panel>

          {/* ------------------------------------------------------- report */}
          <Panel title="Report generator" subtitle="Each report re-runs the operation it describes and exports five formats." dense>
            <div className="space-y-3">
              <Field label="kind">
                <Select value={reportKind} options={REPORT_KINDS.map((entry) => ({ value: entry.value, label: entry.label }))} onChange={setReportKind} />
              </Field>
              <p className="text-[10px] text-[var(--c-faint)]">
                Needs {REPORT_KINDS.find((entry) => entry.value === reportKind)?.needs ?? "—"}.
              </p>
              {reportKind === "comparison" && (
                <Field label="compare against" hint="The second circuit is built from an algorithm in the catalogue.">
                  <Select
                    value={otherAlgorithm}
                    options={(meta?.algorithms ?? []).map((entry) => ({ value: entry.key, label: entry.name }))}
                    onChange={setOtherAlgorithm}
                  />
                </Field>
              )}
              <Field label="title">
                <TextInput value={reportTitle} onChange={setReportTitle} placeholder={`${titleCase(reportKind)} report`} />
              </Field>
              <Field label="objective" hint="Stated in the report itself, so the reader knows what was asked.">
                <TextInput value={reportObjective} onChange={setReportObjective} placeholder="Does noise dominate the result?" />
              </Field>
              <div className="flex flex-wrap gap-2">
                <Button variant="primary" disabled={loading.report} onClick={build}>
                  {loading.report ? "building…" : "build report"}
                </Button>
                <Button
                  variant="outline"
                  onClick={() => {
                    void api
                      .listReports()
                      .then((payload) => {
                        setSavedFiles(payload.files);
                        setSavedDir(payload.dir);
                      })
                      .catch((error: Error) => setLocalError(error.message));
                  }}
                >
                  list saved reports
                </Button>
              </div>
              {localError && <Notice tone="danger">{localError}</Notice>}
              {errors.report && <Notice tone="danger" title="Report refused">{errors.report}</Notice>}

              {savedFiles.length > 0 && (
                <div className="space-y-1">
                  <SectionTitle hint={savedDir}>{savedFiles.length} files on disk</SectionTitle>
                  <div className="max-h-40 space-y-1 overflow-y-auto pr-1">
                    {savedFiles.slice(0, 12).map((file) => (
                      <a
                        key={file.name}
                        href={api.reportFileUrl(file.name)}
                        target="_blank"
                        rel="noreferrer"
                        className="focus-ring flex items-center justify-between gap-2 rounded-md border border-[var(--c-line)] px-2 py-1 text-[10px] hover:border-[var(--c-primary)]"
                      >
                        <span className="truncate">{file.name}</span>
                        <span className="mono-num shrink-0 text-[var(--c-faint)]">
                          {file.format} · {formatBytes(file.bytes)}
                        </span>
                      </a>
                    ))}
                  </div>
                </div>
              )}

              <p className="text-[10px] leading-relaxed text-[var(--c-faint)]">
                Reports are written into the reports directory as HTML, PDF, JSON, CSV and Markdown. The PDF writer is
                part of QScope — no LaTeX or browser engine is needed.
              </p>
            </div>
          </Panel>
        </div>

        {/* ---------------------------------------------------------- answer */}
        <div className="space-y-3">
          {answer ? (
            <Panel
              title={answer.title}
              subtitle={`intent: ${answer.intent} · confidence: ${answer.confidence} · ${answer.grounding}`}
              actions={
                <>
                  <Tag colour="var(--c-secondary)">{answer.confidence}</Tag>
                  <Button size="sm" variant="ghost" onClick={() => void navigator.clipboard?.writeText(answer.body)}>
                    copy answer
                  </Button>
                </>
              }
            >
              <div className="space-y-2">
                {answer.body.split(/\n{2,}/).map((paragraph, index) => (
                  <p key={index} className="text-[12px] leading-relaxed text-[var(--c-text)]">
                    {paragraph}
                  </p>
                ))}
              </div>

              {answer.bullets.length > 0 && (
                <ul className="mt-3 space-y-1.5">
                  {answer.bullets.map((bullet, index) => (
                    <li key={index} className="flex items-start gap-2 text-[11px] leading-relaxed text-[var(--c-muted)]">
                      <span className="mt-[5px] h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--c-primary)]" />
                      {bullet}
                    </li>
                  ))}
                </ul>
              )}

              {answer.citations.length > 0 && (
                <div className="mt-4">
                  <SectionTitle hint="each value was read from the objects above">numbers and where they came from</SectionTitle>
                  <DataTable
                    columns={[
                      { key: "label", label: "quantity" },
                      {
                        key: "value",
                        label: "value",
                        align: "right",
                        render: (row) =>
                          typeof row.value === "number" ? row.value.toPrecision(6) : typeof row.value === "object" ? JSON.stringify(row.value) : String(row.value),
                      },
                      { key: "source", label: "source" },
                    ]}
                    rows={answer.citations as unknown as Array<Record<string, unknown>>}
                  />
                </div>
              )}

              {answer.narrative && (
                <div className="mt-4">
                  <SectionTitle hint={`provider: ${answer.narrative_provider ?? "configured endpoint"}`}>narrative rewrite</SectionTitle>
                  <p className="text-[11px] leading-relaxed text-[var(--c-muted)]">{answer.narrative}</p>
                  {answer.narrative_violations.length > 0 ? (
                    <Notice tone="warn" title="The rewrite introduced numbers that are not in the grounded answer">
                      {answer.narrative_violations.join(" · ")} — the grounded answer above is the authoritative one.
                    </Notice>
                  ) : (
                    <p className="mt-1 text-[10px] text-[var(--c-ok)]">
                      Every number in the rewrite was found in the grounded answer.
                    </p>
                  )}
                </div>
              )}
              {answer.narrative_error && <Notice tone="warn" title="Narration failed">{answer.narrative_error}</Notice>}

              {answer.suggestions.length > 0 && (
                <div className="mt-4">
                  <SectionTitle hint="click to ask">follow-ups the data supports</SectionTitle>
                  <div className="flex flex-wrap gap-1.5">
                    {answer.suggestions.map((suggestion) => (
                      <Button key={suggestion} size="sm" variant="outline" onClick={() => setQuestion(suggestion)}>
                        {suggestion}
                      </Button>
                    ))}
                  </div>
                </div>
              )}

              <div className="mt-4 grid gap-3 lg:grid-cols-2">
                <div>
                  <SectionTitle>limitations stated by the assistant</SectionTitle>
                  <ul className="space-y-1.5">
                    {answer.limitations.map((limitation, index) => (
                      <li key={index} className="flex items-start gap-2 text-[10px] leading-relaxed text-[var(--c-muted)]">
                        <span className="mt-[5px] h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--c-warn)]" />
                        {limitation}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <SectionTitle hint="what the server actually received">sources available</SectionTitle>
                  {answer.sources_available.length === 0 ? (
                    <Empty>No context objects were attached — the assistant answered from the question alone.</Empty>
                  ) : (
                    <div className="flex flex-wrap gap-1.5">
                      {answer.sources_available.map((available) => (
                        <Tag key={available} colour="var(--c-secondary)">
                          {available}
                        </Tag>
                      ))}
                    </div>
                  )}
                  <p className="mt-2 text-[10px] text-[var(--c-faint)]">
                    Attached from this page: {attached.length > 0 ? attached.join(", ") : "nothing yet"}.
                  </p>
                </div>
              </div>
            </Panel>
          ) : (
            <Panel title="The assistant is waiting" subtitle="Ask a question about a circuit, a run, a trace, an optimization or a device.">
              <div className="grid gap-2 sm:grid-cols-2">
                {suggestions.slice(0, 8).map((entry) => (
                  <button
                    key={entry.intent}
                    type="button"
                    onClick={() => setQuestion(entry.question)}
                    className="panel-flat focus-ring px-3 py-2 text-left transition-colors hover:border-[var(--c-primary)]"
                  >
                    <div className="text-[11px] font-medium">{entry.question}</div>
                    <div className="mt-0.5 text-[10px] text-[var(--c-faint)]">intent: {entry.intent}</div>
                  </button>
                ))}
              </div>
              <div className="mt-3 grid gap-2 sm:grid-cols-3">
                <StatTile label="circuit loaded" value={circuit ? `${circuit.num_qubits}q` : "—"} hint={circuit ? `${circuit.resources.gates} gates` : "nothing yet"} />
                <StatTile label="last result" value={result ? result.mode === "NOISY SIMULATION" ? "noisy" : "ideal" : "—"} hint={result ? `${result.shots} shots` : "not executed"} />
                <StatTile label="trace" value={trace ? `${trace.steps.length}` : "—"} hint={trace ? trace.depth_mode : "not traced"} />
                <StatTile label="optimization" value={optimization ? `${optimization.improvements.gates_saved ?? 0}` : "—"} hint="gates saved" />
                <StatTile label="comparison" value={compareResult ? compareResult.mode_a : "—"} hint={compareResult ? "two circuits compared" : "not compared"} />
                <StatTile label="stored runs" value={<AnimatedNumber value={history.length} digits={0} />} hint="available as context" />
              </div>
            </Panel>
          )}

          {reportBody && (
            <InView>
              <Panel
                title={reportBody.title}
                subtitle={`${reportBody.subtitle} · generated ${reportBody.generated_at} · ${reportBody.mode}`}
                actions={
                  <>
                    {(["html", "pdf", "json", "csv", "markdown"] as const).map((format) => (
                      <Button
                        key={format}
                        size="sm"
                        variant="outline"
                        disabled={loading.report}
                        onClick={() => {
                          const request = reportRequest();
                          if (!request.ok) {
                            setLocalError(request.reason);
                            return;
                          }
                          void exportReport(
                            {
                              kind: reportKind,
                              title: reportTitle || `${titleCase(reportKind)} report`,
                              objective: reportObjective || null,
                              save: false,
                              payload: request.payload,
                            },
                            format,
                          );
                        }}
                      >
                        {format === "markdown" ? "md" : format}
                      </Button>
                    ))}
                  </>
                }
              >
                <p className="text-[11px] leading-relaxed text-[var(--c-muted)]">
                  <span className="label-xs mr-2">objective</span>
                  {reportBody.objective}
                </p>

                <div className="mt-3 space-y-4">
                  {reportBody.sections.map((section, index) => (
                    <div key={`${section.heading}-${index}`}>
                      <SectionTitle hint={section.kind}>{section.heading}</SectionTitle>
                      {renderBody(section.body)}
                      {(section.note || section.caption) && (
                        <p className="mt-1 text-[10px] leading-relaxed text-[var(--c-faint)]">
                          {section.note} {section.caption}
                        </p>
                      )}
                    </div>
                  ))}
                </div>

                {reportBody.observations.length > 0 && (
                  <div className="mt-4">
                    <SectionTitle>observations</SectionTitle>
                    <ul className="space-y-1.5">
                      {reportBody.observations.map((observation, index) => (
                        <li key={index} className="flex items-start gap-2 text-[11px] leading-relaxed text-[var(--c-muted)]">
                          <span className="mt-[5px] h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--c-primary)]" />
                          {observation}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {reportBody.limitations.length > 0 && (
                  <div className="mt-4">
                    <SectionTitle>limitations</SectionTitle>
                    <ul className="space-y-1.5">
                      {reportBody.limitations.map((limitation, index) => (
                        <li key={index} className="flex items-start gap-2 text-[11px] leading-relaxed text-[var(--c-muted)]">
                          <span className="mt-[5px] h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--c-warn)]" />
                          {limitation}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="mt-4">
                  <SectionTitle>conclusion</SectionTitle>
                  <p className="text-[12px] leading-relaxed text-[var(--c-text)]">{reportBody.conclusion}</p>
                </div>

                <div className="mt-4 grid gap-3 lg:grid-cols-2">
                  <div>
                    <SectionTitle hint="recorded with the report">reproducibility</SectionTitle>
                    <KeyValueList
                      columns={2}
                      items={Object.entries(reportBody.reproducibility).map(([label, value]) => ({
                        label: label.replace(/_/g, " "),
                        value: typeof value === "object" && value !== null ? JSON.stringify(value) : String(value ?? "—"),
                      }))}
                    />
                  </div>
                  <div>
                    <SectionTitle hint="saved to disk">exports</SectionTitle>
                    {report?.files ? (
                      <div className="space-y-1">
                        {Object.entries(report.files).map(([format, path]) => {
                          const name = path.split(/[\\/]/).pop() ?? path;
                          return (
                            <a
                              key={format}
                              href={api.reportFileUrl(name)}
                              target="_blank"
                              rel="noreferrer"
                              className="focus-ring mono-num block truncate rounded-md border border-[var(--c-line)] px-2 py-1 text-[10px] hover:border-[var(--c-primary)]"
                              title={path}
                            >
                              {format}: {name}
                            </a>
                          );
                        })}
                      </div>
                    ) : (
                      <Empty>Not saved to disk. The export buttons above render the same report on demand.</Empty>
                    )}
                  </div>
                </div>

                <div className="mt-4">
                  <SectionTitle hint="the same report, in text">markdown</SectionTitle>
                  <CodeBlock text={report?.markdown ?? ""} caption="report.md" maxHeight={320} />
                </div>
              </Panel>
            </InView>
          )}
        </div>
      </div>
    </div>
  );
}
